name: Deploy pipeline

concurrency:
  group: deploy
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
    deploy-front-app:
    name: Deploy front-app
    runs-on: ubuntu-24.04

    steps:
      - name: Check artifact exists
        uses: xSAVIKx/artifact-exists-action@v0
        id: check_coverage_artifact
        with:
          name: front-app-${{ github.sha }}

      - name: Copy artifact
        if: steps.check_coverage_artifact.outputs.exists == 'true'
        uses: garygrossgarten/github-action-scp@release
        with:
          local: front-app-${{ github.sha }}
          remote: /var/www/front-app
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy front-app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/front-app
            ls -la
            