name: Deploy pipeline

concurrency:
  group: deploy
  cancel-in-progress: true

env:
  FRONT_ARTIFACT_NAME: 'front-app-build'

on:
  workflow_dispatch:

jobs:
  check-front-app-artifact-exists:
    name: Check front-app artifact exists
    runs-on: ubuntu-24.04

    steps:
      - name: Check artifact exists
        uses: xSAVIKx/artifact-exists-action@v0
        id: check_coverage_artifact
        with:
          name: ${{ env.FRONT_ARTIFACT_NAME }}

  copy-front-app-artifact:
    name: Copy front-app artifact
    runs-on: ubuntu-24.04
    needs: check-front-app-artifact-exists

    if: needs.check-front-app-artifact-exists.outputs.exists

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.FRONT_ARTIFACT_NAME }}

      - name: Copy artifact
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ${{ env.FRONT_ARTIFACT_NAME }}
          remote: /var/www/front-app
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

  deploy-front-app:
    name: Deploy front-app
    runs-on: ubuntu-24.04
    needs: copy-front-app-artifact

    steps:
      - name: Deploy front-app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/front-app
            ls -la
