name: Main pipeline

env:
  PNPM_VERSION: '8'
  NODE_VERSION: '20'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    strategy:
      matrix:
        app: [front-app, back-app]
    name: Lint ${{ matrix.app }}

    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: ${{ matrix.app }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: './${{ matrix.app }}/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: Lint app
        run: pnpm lint

  build-front-app:
    name: Build front-app
    needs: lint

    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: front-app

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: './front-app/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: pnpm build

      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: front-app-build-${{ github.sha }}
          path: front-app/dist