name: Main pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-front-app:
    name: Lint front-app

    runs-on: ubuntu-latest

    concurrency:
      group: pre-build
      cancel-in-progress: true

    defaults:
      run:
        working-directory: front-app

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: './front-app/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: Lint app
        run: pnpm lint

  lint-back-app:
    name: Lint back-app

    runs-on: ubuntu-latest

    concurrency:
      group: pre-build
      cancel-in-progress: true

    defaults:
      run:
        working-directory: back-app

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: './back-app/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: Lint app
        run: pnpm lint

  build-front-app:
    name: Build front-app
    needs: pre-build

    runs-on: ubuntu-latest

    concurrency:
      group: build
      cancel-in-progress: true

    defaults:
      run:
        working-directory: front-app

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: './front-app/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: pnpm build