name: Main pipeline

env:
  PNPM_version: ${{ env.PNPM_VERSION }}
  NODE_VERSION: 20

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-front-app:
    name: Lint front-app

    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: front-app

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: './front-app/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: Lint app
        run: pnpm lint

  lint-back-app:
    name: Lint back-app

    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: back-app

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: './back-app/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: Lint app
        run: pnpm lint

  build-front-app:
    name: Build front-app
    needs: [lint-front-app, lint-back-app]

    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: front-app

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: './front-app/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: pnpm build